layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  skype: skype:live:mihai_olteanu_2?chat
  facebook: mihai.olteanu.395
  # linkedin: your_username
  stackoverflow: 2819719
  # website: http://your_website_url

topics:
  - name: Common Lisp
    web_url: https://github.com/topics/common-lisp
    image_url: https://sdl-stickershop.line.naver.jp/products/0/0/1/1299646/android/stickers/12120446.png

  - name: C (Embedded)

  - name: Emacs
    image_url: https://shop.fsf.org/sites/default/files/styles/product_zoom/public/Emacs-icon.sh_.png

  - name: ArchLinux
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Archlinux-icon-crystal-64.svg/1024px-Archlinux-icon-crystal-64.svg.png

  - name: Bash
    image_url: https://miro.medium.com/max/630/1*FEE98iWinlZBYkxBAG8MvA.png
